# params.yaml
base:
  seed: 42

prepare:
  split: 0.2 # Test set ratio

train:
  model_type: MLPClassifier
  hidden_layer_sizes: [150, 100, 50]  # Three hidden layers with 150, 100, and 50 neurons
  max_iter: 1000
  activation: 'relu'
  solver: 'adam'
  random_state: 42